const RECOVERY_PHRASE_LENGTH = 24;
const EMTQ_DIVISIBILITY = 8;
const POWER_DIVISIBILITY = Math.pow(10, EMTQ_DIVISIBILITY);
const FEE = 0.01;

export {
  RECOVERY_PHRASE_LENGTH,
  EMTQ_DIVISIBILITY,
  POWER_DIVISIBILITY,
  FEE,
};