openapi:  3.0.1
info:
  title: Emotiq Wallet interface
  version: 0.0.2
tags:
  - name: consensus
  - name: wallet
  - name: transaction
  - name: dictionary
paths:
  /consensus/:
    get:
      tags:
        - consensu
      summary: >-
        Returns information about current chain consensus with the connected
        node
      responses:
        '200':
          description: Consensus information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/consensus'
  /wallet/:
    get:
      tags:
        - wallet
      description: Enumerate the names of existing wallets on this node
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /wallet/{name}/create:
    post:
      tags:
        - wallet
      summary: Create wallet
      parameters:
        - name: name
          in: path
          description: |-
            Name of wallet to create
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    description: |-
                      Public address of the newly created wallet
                    type: string
        '409':
          description: Wallet already exists
  /wallet/{name}:
    delete:
       summary: Delete the named wallet
       parameters:
         - name: name
           in: path
           description: The name of the wallet to delete
           required: true
           schema:
             type: string
       responses:
          '204':
            description: The named wallet was successfully deleted
          '404':
            description: The named wallet does not exist
  /wallet/{name}/restore:
    post:
      tags:
        - wallet
      operationId: restoreWallet
      requestBody:
        description: Phrase to be used to restore wallet
        required: true
        content:
            application/json:
              schema:
                type: object
                properties:
                  recoveryPhrase:
                    type: string
      parameters:
        - name: name
          description: Name of the wallet to restore
          in: path
          required: true
          schema:
            type: string
          
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
        '409':
          description: Wallet already exists
          
components:
  schemas:
    consensus:
      type: object
      properties:
        epoch:
          description: The number of the last sealed epoch
          type: integer
        synced:
          description: Whether the connected node is synced with the chain
          type: boolean
    transaction:
      type: object
      properties:
        id:
          type: string
        timestamp:
          type: integer
          format: int64
        inputs:
          type: array
          items:
            type: object
            properties:
              cloaked:
                type: boolean
              address:
                type: string
              amount:
                type: integer
        outputs:
          type: array
          items:
            type: object
            properties:
              cloaked:
                type: boolean
              address:
                type: string
              amount:
                type: integer
