const SET_PASSWORD = 'SET_PASSWORD';
const WRITE_DOWN_RECOVERY_PHRASE = 'WRITE_DOWN_RECOVERY_PHRASE';
const RESTORE_WALLET = 'RESTORE_WALLET';
const DELETE_WALLET = 'DELETE_WALLET';

export {
  SET_PASSWORD,
  WRITE_DOWN_RECOVERY_PHRASE,
  RESTORE_WALLET,
  DELETE_WALLET,
}