const SET_PASSWORD = 'SET_PASSWORD';
const WRITE_DOWN_RECOVERY_PHRASE = 'WRITE_DOWN_RECOVERY_PHRASE';
const RESTORE_WALLET = 'RESTORE_WALLET';
const DELETE_WALLET = 'DELETE_WALLET';
const RENAME_WALLET = 'RENAME_WALLET';
const SET_ADDRESSES = 'SET_ADDRESSES';
const SET_AMOUNT = 'SET_AMOUNT';
const ADD_TRANSACTION = 'ADD_TRANSACTION';

export {
  SET_PASSWORD,
  WRITE_DOWN_RECOVERY_PHRASE,
  RESTORE_WALLET,
  DELETE_WALLET,
  RENAME_WALLET,
  SET_ADDRESSES,
  SET_AMOUNT,
  ADD_TRANSACTION,
};